In [48]:
from collections import Counter, deque
from itertools import permutations
import random

In [44]:
x ='aasssddddsavv'
str1 = Counter(x)
s = deque()
print(str1)
str2 = str1.keys()
s.append(1)
s.appendleft(7)
s.extendleft([3, 1, 7])
s

Counter({'s': 4, 'd': 4, 'a': 3, 'v': 2})


deque([7, 1, 3, 7, 1])

In [51]:
a = [1, 2, 5, 67, 9, 21]
a1 = 1.5
perm = permutations(a, 2)
print(list(perm))

[(1, 2), (1, 5), (1, 67), (1, 9), (1, 21), (2, 1), (2, 5), (2, 67), (2, 9), (2, 21), (5, 1), (5, 2), (5, 67), (5, 9), (5, 21), (67, 1), (67, 2), (67, 5), (67, 9), (67, 21), (9, 1), (9, 2), (9, 5), (9, 67), (9, 21), (21, 1), (21, 2), (21, 5), (21, 67), (21, 9)]


In [52]:
b = map(lambda x: x*2, a)
b1 = lambda x: x*2
b2 = filter(lambda x: x%2 == 1, a)
print(list(b))
print(b1(a))
print(list(b2))

[2, 4, 10, 134, 18, 42]
[1, 2, 5, 67, 9, 21, 1, 2, 5, 67, 9, 21]
[1, 5, 67, 9, 21]


In [90]:
import numpy as np
print(random.random())
print(random.random())
print(random.randint(5, 10))
#print(np.random.random(4))
arr = np.random.uniform(1, 20, (3,3))
print(np.round(arr, 2))
np.random.randint(1, 20, (3,3))

0.5153922053540086
0.7962162446523026
10
[[ 9.25 16.8   5.48]
 [15.29 12.51  7.06]
 [19.69  8.58 19.2 ]]


array([[ 5,  7,  6],
       [12, 14,  6],
       [13,  9,  4]])

In [1]:
print('hello')

hello


In [1]:
import requests
import pandas as pd

In [3]:
req = requests.get('https://date.nager.at/api/v3/publicholidays/2019/ID')
req.status_code

200

In [6]:
pd.DataFrame(req.json())

date                                        localName  \
0  2019-01-01                                Tahun Baru Masehi   
1  2019-04-19                                Wafat Isa Almasih   
2  2019-04-21                                           Paskah   
3  2019-05-01                         Hari Buruh Internasional   
4  2019-05-30                             Kenaikan Isa Almasih   
5  2019-06-01                             Hari Lahir Pancasila   
6  2019-08-17  Hari Ulang Tahun Kemerdekaan Republik Indonesia   
7  2019-12-25                                  Hari Raya Natal   

               name countryCode  fixed  global counties  launchYear     types  
0    New Year's Day          ID   True    True     None         NaN  [Public]  
1       Good Friday          ID  False    True     None         NaN  [Public]  
2     Easter Sunday          ID  False    True     None         NaN  [Public]  
3        Labour Day          ID   True    True     None         NaN  [Public]  
4     Ascension Day          ID  False    True     None         NaN  [Public]  
5     Pancasila Day          ID   True    True     None      2017.0  [Public]  
6  Independence Day          ID   True    True     None         NaN  [Public]  
7     Christmas Day          ID   True    True     None         NaN  [Public]

In [9]:
req = requests.get('https://randomuser.me/api/?nat=id')
bio =req.json()

In [13]:
bio = bio['results'][0]

In [16]:
bio

{'gender': 'female',
 'name': {'title': 'Mrs', 'first': 'Lola', 'last': 'Boyer'},
 'location': {'street': {'number': 9405, 'name': 'Rue Barrème'},
  'city': 'Nancy',
  'state': 'Vendée',
  'country': 'France',
  'postcode': 75084,
  'coordinates': {'latitude': '3.3852', 'longitude': '118.6424'},
  'timezone': {'offset': '-6:00',
   'description': 'Central Time (US & Canada), Mexico City'}},
 'email': 'lola.boyer@example.com',
 'login': {'uuid': '9173f69f-b407-4f2e-8285-4e53f0cb8f3e',
  'username': 'goldenelephant919',
  'password': 'lesbain',
  'salt': 'taC8l3Yi',
  'md5': '663bc10a5485ef306050a88ebe6b9da1',
  'sha1': 'f4336489776bfc5a51662e088c9219c920137b98',
  'sha256': 'b50dabdfb3e6a131f900f40090bfc4fb170c12f8eee5d38f741dd530a837d7e7'},
 'dob': {'date': '1962-09-03T05:27:08.769Z', 'age': 60},
 'registered': {'date': '2005-11-05T10:01:13.982Z', 'age': 17},
 'phone': '01-77-59-28-83',
 'cell': '06-76-49-84-65',
 'id': {'name': 'INSEE', 'value': '2NNaN14417053 26'},
 'picture': {'larg

In [17]:
info = bio['name']['first']
info

'Lola'

In [21]:
biodata = {
    'first_name' : bio['name']['first'],
    'last_name' : bio['name']['last'],
    'gender' : bio['gender'],
    'birth' : bio['dob']['date']
}
biodata

{'first_name': 'Lola',
 'last_name': 'Boyer',
 'gender': 'female',
 'birth': '1962-09-03T05:27:08.769Z'}

In [22]:
from dateutil import parser

date = parser.parse(biodata['birth'])
date = date.strftime('%d-%m-%y')
date

'03-09-62'

In [23]:
biodata['birth'] = date
biodata

{'first_name': 'Lola',
 'last_name': 'Boyer',
 'gender': 'female',
 'birth': '03-09-62'}