In [48]:
from collections import Counter, deque
from itertools import permutations
import random

In [44]:
x ='aasssddddsavv'
str1 = Counter(x)
s = deque()
print(str1)
str2 = str1.keys()
s.append(1)
s.appendleft(7)
s.extendleft([3, 1, 7])
s

Counter({'s': 4, 'd': 4, 'a': 3, 'v': 2})


deque([7, 1, 3, 7, 1])

In [51]:
a = [1, 2, 5, 67, 9, 21]
a1 = 1.5
perm = permutations(a, 2)
print(list(perm))

[(1, 2), (1, 5), (1, 67), (1, 9), (1, 21), (2, 1), (2, 5), (2, 67), (2, 9), (2, 21), (5, 1), (5, 2), (5, 67), (5, 9), (5, 21), (67, 1), (67, 2), (67, 5), (67, 9), (67, 21), (9, 1), (9, 2), (9, 5), (9, 67), (9, 21), (21, 1), (21, 2), (21, 5), (21, 67), (21, 9)]


In [52]:
b = map(lambda x: x*2, a)
b1 = lambda x: x*2
b2 = filter(lambda x: x%2 == 1, a)
print(list(b))
print(b1(a))
print(list(b2))

[2, 4, 10, 134, 18, 42]
[1, 2, 5, 67, 9, 21, 1, 2, 5, 67, 9, 21]
[1, 5, 67, 9, 21]


In [90]:
import numpy as np
print(random.random())
print(random.random())
print(random.randint(5, 10))
#print(np.random.random(4))
arr = np.random.uniform(1, 20, (3,3))
print(np.round(arr, 2))
np.random.randint(1, 20, (3,3))

0.5153922053540086
0.7962162446523026
10
[[ 9.25 16.8   5.48]
 [15.29 12.51  7.06]
 [19.69  8.58 19.2 ]]


array([[ 5,  7,  6],
       [12, 14,  6],
       [13,  9,  4]])

In [1]:
print('hello')

hello
